baseurl: 'https://agnivamahata.com'
languageCode: en-us
title: Agniva Mahata
googleAnalytics: ""
disqusShortname: ""
disableHugoGeneratorInject: true
pluralizeListTitles: false
enableRobotsTXT: true
minify:
  minifyOutput: true

pagination:
  pagerSize: 9999

taxonomies:
  tag: tags

permalinks:
  writing: /:year/:month/:day/:slug/

params:
  description: ""
  subtitle: ""

frontmatter:
  author:
  github:
  facebook:
  og_image:
  sitename:
  twitter:

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.9

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
